version: "3.8"
services:
  tts-backend:
    build:
      context: ./Backend
    ports:
      - "5000:5000"

  tts-frontend:
    build:
      context: ./Frontend
    ports:
      - "3000:80"
    depends_on:
      - tts-backend
